### ISSUE TITLE
Syntax error def read_datetime(value: str) -> datetime.datetime:

### ISSUE THREAD

**Issue by holmesrichards** [bneijt/autotrash#25]
I am getting this:

$ autotrash -d 30
Traceback (most recent call last):
  File "/home/rsholmes/.local/bin/autotrash", line 5, in <module>
    from autotrash.app import main
  File "/home/rsholmes/.local/lib/python2.7/site-packages/autotrash/__init__.py", line 8, in <module>
    from .app import *
  File "/home/rsholmes/.local/lib/python2.7/site-packages/autotrash/app.py", line 104
    def read_datetime(value: str) -> datetime.datetime:
                           ^
SyntaxError: invalid syntax

Using recently downloaded autotrash, Linux Mint 20 Cinnamon

**Comment by bneijt** [comment]
The syntax problem is with Python 2, which is no-longer supported because of the type annotations I added.

See which python /home/rsholmes/.local/bin/autotrash points to by opening it with a text editor. It is _probably_ pointing to /usr/bin/python which is _probably_ a python 2 installation.

You can change that to Python 3. I would have to see if I can make some kind of adjustment to enforce a newer python being used, because you probably have Python 3 on your system already as python 2 is being deprecated ( https://www.python.org/doc/sunset-python-2/ )

Could you get back to me on if Python 3 solves it?

Thank you for posting!

**Comment by holmesrichards** [comment]
Thanks, I'd been considering finally giving in and making python3 the default. I have now done so. I had to re-install autotrash but once I did it looks like it's working.
